# Site settings
title: Apache Myriad 
email: dev@myriad.incubator.apache.org
description: > # this means to ignore newlines until "baseurl:"
    Deploy Apache YARN Applications Using Apache Mesos
    Apache Myriad enables the co-existence of Apache Hadoop and Apache Mesos
    on the same physical infrastructure. By running Hadoop YARN as a Mesos 
    framework, YARN applications and Mesos frameworks can run side-by-side, 
    dynamically sharing cluster resources.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://myriad.incubator.apache.org" # the base hostname & protocol for your site
twitter_username: apachemyriad
# Build settings
markdown: kramdown
